### ISSUE TITLE
PoE turns on and off with Netgear GS308P

### ISSUE THREAD

**Issue by sbourdeauducq** [sinara-hw/Stabilizer#23] opened 2019-06-26 02:15 UTC
When connected to a Netgear GS308P switch, the board is powered for a few seconds, then the Ethernet link establishes, then the switch cuts off power, and the cycle repeats.
After a few cycles, sometimes the board stays powered on.

**Comment by sbourdeauducq** [comment] 2019-07-10 08:36
Problem is not present on a second board.

**Comment by gkasprow** [comment] 2019-07-10 09:44
It may be a result of slightly different capacitance tolerance causing a small difference in startup current

**Comment by gkasprow** [comment] 2019-08-29 14:58
Should I buy such a switch and try to solve the issue or we can assume that the user must use 30W power delivery? I don't have any stabilizer board in my lab.

**Comment by hartytp** [comment] 2019-09-06 20:45
What should we do about this?

**Comment by gkasprow** [comment] 2019-09-06 21:39
I'm not able to recreate the issue right now. All PoE switches I have in my lab work fine.

**Comment by hartytp** [comment] 2019-09-07 06:45
Can you think of anything that might have caused this on one of @sbourdeauducq's boards? Or do you think it was a defective board?

@sbourdeauducq can you send Greg the problematic board and switch?

**Comment by sbourdeauducq** [comment] 2019-09-07 12:24
I already sent the board back, the switch is in use 24/7.

**Comment by hartytp** [comment] 2019-09-07 12:28
Sounds like an isolated incident maybe with one board. Shall we close for now and reopen if we see this again?

**Comment by sbourdeauducq** [comment] 2019-09-07 12:40
As Greg explained earlier, it could be that the board is near the maximum for low-power PoE injectors and component tolerances put it on one side or the other of the limit.

**Comment by hartytp** [comment] 2019-09-07 15:04
Which component tolerances? What do we want to do about this issue?

**Comment by sbourdeauducq** [comment] 2019-09-07 15:05
If the solution is to reduce inrush current, we should fix it.

**Comment by gkasprow** [comment] 2019-09-07 16:01
But, the issue appeared once the Ethernet LEDs went on. It means it is not inrushed current of the DC/DC converters but current consumption of the Ethernet chip or something else which triggers the overcurrent protection.
I wouldn't do any design changes until we make sure what causes this issue.
The Stabilizer has multi-stage power sequencing and the 3V3 wakes up after 5V rail
So it looks like the OVC is triggered by +/-12V LDO, because it turns on just after the 3V3 rail.
The opamps may consume some excessive current before they reach working voltage.
Can you connect the scope to +12V input rail, +3V3, +- 12VA and +5V ?
Trigger it on falling +12V and see what rail causes the issue.

**Comment by hartytp** [comment] 2019-09-07 18:30
@gkasprow do you have a stabilizer card? If so, this is easy isn't it? Replace L6 with a 0R1/0R01 resistor and look at the voltage across that resistor with a differential probe while you power stabilizer on. That will tell you the current v time profile during startup. If that's marginal according to the PoE specification then we should fix it, if not I think we can assume that there was an issue with the specific board that @sbourdeauducq had.

**Comment by dtcallcock** [comment] 2019-09-07 18:35
How important is it that POE is supported by Sinara boards given POE+ kit doesn't seem that hard to come by?  For example that GS308P (8 port | 4xPoE 53W) is a $70 switch but the GS108LP (8 port | 8xPoE+ 60W) switch is only $85.

**Comment by hartytp** [comment] 2019-09-07 18:37
It's a nice to have, as it saves on the external clutter of having PoE splitters. It's particularly useful for small modules like Thermostat where one might want to get them into a tight space with limited cabling access.

**Comment by gkasprow** [comment] 2019-09-07 18:41
The question is about scrapping POE(802.3af) and support only PoE+ (802.3at) switches

**Comment by dtcallcock** [comment] 2019-09-07 18:41
This ^

**Comment by hartytp** [comment] 2019-09-07 18:43
aah, ok.

While I don't feel too strongly, I'd prefer to keep 802.3af support unless it turns out to be particularly hard to do. The reason being that it's likely that users will get confused about the distinction and use the wrong PoE switch type anyway.

**Comment by gkasprow** [comment] 2019-09-07 19:17
The design supports, but @sbourdeauducq found a single case where it doesn't work. So, if we want to support standard PoE, one needs to debug it.

**Comment by hartytp** [comment] 2019-09-07 20:40
Replaced L6 with 1R0 to monitor current transients during power on. Powering from external 12V supply via barrel connector.

![image](https://user-images.githubusercontent.com/21218399/64480027-12234600-d1b8-11e9-8249-7b49993f5d14.png)

**Comment by hartytp** [comment] 2019-09-07 20:42
Peak is 690mA. So only 8W

![image](https://user-images.githubusercontent.com/21218399/64480036-4eef3d00-d1b8-11e9-890f-12f1b955f63a.png)

**Comment by hartytp** [comment] 2019-09-07 20:46
Longer time scale 
![image](https://user-images.githubusercontent.com/21218399/64480053-937ad880-d1b8-11e9-9c5e-b3ca6b91d35c.png)

**Comment by hartytp** [comment] 2019-09-07 20:47
even longer 
![image](https://user-images.githubusercontent.com/21218399/64480084-1dc33c80-d1b9-11e9-8179-4c847bae8db8.png)

**Comment by hartytp** [comment] 2019-09-07 20:51
So, no sign of anything bad there. GS308P is specified for 15.4W per channel and our peak power is just over half that.

![image](https://user-images.githubusercontent.com/21218399/64480110-a04bfc00-d1b9-11e9-92da-9fccf79f3880.png)

I'll try again with a PoE switch to be sure.

**Comment by hartytp** [comment] 2019-09-07 20:54
Now with a netgear prosafe jgs516pe

![image](https://user-images.githubusercontent.com/21218399/64480127-e86b1e80-d1b9-11e9-9ae4-88ec837155ba.png)

![image](https://user-images.githubusercontent.com/21218399/64480135-15b7cc80-d1ba-11e9-9d64-63747ca16941.png)

**Comment by hartytp** [comment] 2019-09-07 20:57
So, based on that, I think we can rule out inrush currents from being an issue on Stabilizer.

Unless anyone can think of anything else that could be the issue here and ,given that we cannot reproduce this issue and we no longer have access to the board it manifested on, I suggest we close this for now and repoen/debug if it occurs again. Any objections?

**Comment by hartytp** [comment] 2019-09-07 21:27
hmm...one possibility here is that the real issue is the reference buffer oscillating on your board (due to the lack of decoupling). That's really marginal and is completely unstable on some boards. That can sink a hell of a lot of current into the decoupling caps.

Anyway, we've done some work on rail stability in general, so maybe that will help...

**Comment by hartytp** [comment] 2019-09-08 00:09
Nb if you have cheap Ethernet cables with high resistamce you’ll have issues like this due to loss in the cables during the turn on current spikes

**Comment by hartytp** [comment] 2019-09-10 19:07
Okay, closing for now. Let's reopen if anyone is able to reproduce similar symptoms, or if anyone can think of any further tests we should do

**Comment by sbourdeauducq** [comment] 2019-09-11 00:58
I am using high-quality short Ethernet cables and I had already tried to replace them, without effect. They also power other devices correctly.

**Comment by hartytp** [comment] 2019-09-11 08:30
@sbourdeauducq noted. But, without access to hardware that displays this issue, I don't see any good way of debugging it further. e.g. from the sounds of it, this could have been a QC issue like a short on the PoE module rather than a design fault.

**Comment by hartytp** [comment] 2019-09-11 08:41
Note to self, the spec is 

![image](https://user-images.githubusercontent.com/21218399/64681316-6576ec00-d477-11e9-983b-c9836ff16509.png)

=

**Comment by hartytp** [comment] 2019-09-11 08:54
hmm...it's possible that the issue here is that we're right on the edge of the PoE module's minimum load specification. cf #50. Again, however, hard to tell witout hardware (if we had it, we could add a load resistor to the board and see if that fixed the problem).

**Comment by hartytp** [comment] 2019-09-11 08:55
We're nowhere near maximum current. Assume Vi = 37V, efficiency=0.8, Iout_peak=700mA. Peak input current is then 280mA, which is comfortably within spec.

**Comment by hartytp** [comment] 2019-09-11 08:56
Anyway, from a design review of the PoE design, the only potential issues I can see are the min load and the missing ESD diode. Other pairs of eyes always welcome!

**Comment by sbourdeauducq** [comment] 2019-09-18 10:06
@gkasprow I can send the switch now. Technosystem have the problematic board already.

**Comment by gkasprow** [comment] 2019-09-18 13:18
OK, let's sort this out before next  revision

**Comment by gkasprow** [comment] 2019-10-21 13:58
I got the board. I also have a switch but it works. The switch is, however, AF/AT. I ordered Netgear GS308P, the same @sbourdeauducq has. It is AF only.

**Comment by hartytp** [comment] 2019-10-21 16:53
I can reproduce this on a thermostat board. Interestingly, the first time I plugged it into PoE I got a green light on my switch. After that, each time I plugged it in, I get an error light and the power cycles on/off. Powering from a barrel connector it seems fine (5V, 3V3 and 3V3A all have the correct voltage).

@gkasprow what measurements should I take on this thermostat board to help narrow down the issue?

**Comment by hartytp** [comment] 2019-10-21 17:28
@gkasprow on this Thermostat, the PoE switch error LED blinks on/off for a while before eventually giving me a green LED. Someone (you??) kindly soldered antennae to the PoE rectifier diodes to make them easy to probe. Screen shorts below

**Comment by hartytp** [comment] 2019-10-21 17:30
PoE + and PoE -  (all using 10x DC-coupled probes)

![image](https://user-images.githubusercontent.com/21218399/67228208-babbfb00-f430-11e9-9d95-45de32845988.png)

Same but zoomed in time scale

![image](https://user-images.githubusercontent.com/21218399/67228243-ca3b4400-f430-11e9-92d0-e2149edef1d6.png)

**Comment by hartytp** [comment] 2019-10-21 17:32
Same but channel 2 now looking at the +12V output of the PoE module:

![image](https://user-images.githubusercontent.com/21218399/67228369-02428700-f431-11e9-9f82-d770edd8636b.png)

![image](https://user-images.githubusercontent.com/21218399/67228423-23a37300-f431-11e9-9cd0-b1ca00e56d92.png)


![image](https://user-images.githubusercontent.com/21218399/67228398-14bcc080-f431-11e9-8da8-51a7ebb2baf5.png)

In the last shot you can see the power come on and stay on

**Comment by gkasprow** [comment] 2019-10-21 17:42
I think we have to look at the current. For such measurements, I use battery-powered scope

**Comment by hartytp** [comment] 2019-10-21 18:04
hmm...I think some of the photos above look odd because the scope probe came disconnected and so was basically AC coupled. I've got better photos I'll post later.

> I think we have to look at the current. For such measurements, I use battery-powered scope

That was my thought too. But, it's not totally straightforward since there is no easy place to probe (will probably have to life a rectifier diode and solder a sense resistor between the diode and its pad) and I'll be measuring a small signal on a large offset. I'll try that, but won't be for a couple of days.

What I may have time for later this eve would be to try adding a load resistor to the 12V output. That could tell us if it's the switch being fussy over minimum loads.

**Comment by gkasprow** [comment] 2019-10-21 19:07
I will play with it once I get a switch with 15W power delivery. All the switches I own are 30W ones

**Comment by hartytp** [comment] 2019-10-21 19:08
Cutting the PoE+ trace and adding a 100Ohm sense resistor seems to "fix" the issue. No idea why yet. Vsense=1.5V, so input current is 15mA or approx 75mW.

**Comment by hartytp** [comment] 2019-10-21 19:10
So, it sounds like this may just be a surge current issue. I bet that if I was using a long/cheap ethernet cable I wouldn't be able to reproduce this. The EMI filter in the next revision will almost certainly do the job.

I'll try a 10Ohm sense resistor and see if I can still reproduce the issue. But, it may be that any resistor large enough to give me a sensible reading is also large enough to stop the PSU from tripping...

**Comment by hartytp** [comment] 2019-10-21 19:14
Still boots reliably with 10Ohm

**Comment by hartytp** [comment] 2019-10-21 19:32
Probing across my sense resistor, I can't see any transients. So, maybe there is some funny instability that only occurs when the input resistance to the PoE module is too low.

FWIW adding a 150R load resistor to the 12V output didn't help, suggesting that it really is an issue with the input, not a violation of the minimum current.

Putting a 0R resistor back in and the problem promptly returns. 

A longer ethernet cable didn't fix the problem.

**Comment by hartytp** [comment] 2019-10-21 19:35
NB the resistor I added was between the PoE module pin 1 and the diodes.

@gkasprow I wasn't able to find a sense resistor largel enough to give me a current signal I could measure easily, which didn't make the issue go away...

What do you think about all of this? Any more measurements we should take? Or, shall we just hope that the EMI filter resolves the issue, but leave pads for some small damping resistors between the module and the diodes just in case.

The only issue is if we want to draw close to max power: 25W at 50V is 0.5A, so even 1Ohm would be 0.5W! Let's just hope the EMI filter fixes the issue!

**Comment by hartytp** [comment] 2019-10-21 19:35
@gkasprow what do you think?

**Comment by hartytp** [comment] 2019-10-21 19:49
FWIW a 22uH coil craft chip inductor (DCR~11Ohm) also fixes the issue. So, I'm now relatively optimistic that this will not be present in the new revision with the EMI filter.

I am, however, concerned about the power handling of the EMI filter on Thermostat, but that's a separate issue.

@jordens @gkasprow any objections to closing this issue? 

@gkasprow we really need to get the next batch of Stabilizer sent to manufacture this week. AFAICT, so long as no one has any more concerns about this issue, there is very little to do. Would you mind finishing off and preparing for manufacture asap please? Thanks!!

**Comment by hartytp** [comment] 2019-10-21 19:54
> I will play with it once I get a switch with 15W power delivery. All the switches I own are 30W ones

FYI My switch is 30W as well. For some reason I can only reproduce this on some switch channels on some boards, so I think it's something being very marginal. Anyway, I think I now have all the data we need on this...

**Comment by gkasprow** [comment] 2019-10-21 20:27
OK, let's close and hope this will resolve the issue.

**Comment by hartytp** [comment] 2019-10-21 20:28
Ok. As I said, if you think of any more measurements we should take, let me know.

**Comment by gkasprow** [comment] 2019-10-23 16:32
I received the Netgear GS308P switch and I can confirm - the Stabilizer turns on for 3-4s, then turns off for another 3s and the cycle repeats. Now, I can debug this issue.

**Comment by gkasprow** [comment] 2019-10-25 17:26
I placed 5Ohm resistor in series with PoE converter and it starts just fine. There is 0.3V drop on it.

**Comment by gkasprow** [comment] 2019-10-25 17:30
I tried with the 100nF capacitor between G and S of T5 but it does not help. It looks like it's the PoE converter that causes a current spike.

**Comment by hartytp** [comment] 2019-10-25 17:30
> I placed 5Ohm resistor in series with PoE converter and it starts just fine. There is 0.3V drop on it.

That's roughly consistent with my observations. I found it hard to pick a small enough resistor to avoid interfering in the dynamics, while still getting a measurable signal.

What did the transients look like? 300mV on 5Ohm = 60mA. 

Can you try putting an inductor in series with the PoE module? AFAICT, this also fixes the problem. It would be nice to see the current transients when the fault occur (although, that's hard to measure). But, AFAICT, any input filtering will resolve the issue.

**Comment by gkasprow** [comment] 2019-10-25 17:35
1R resistor is too low.

**Comment by hartytp** [comment] 2019-10-25 17:35
Too low? As in, too low to measure the current, or as in with 1Ohm the fault is still present?

**Comment by gkasprow** [comment] 2019-10-25 17:38
with 1Ohm the issue still exists.
I placed 47uH inductor and it did not help.

**Comment by hartytp** [comment] 2019-10-25 17:39
Interesting. Can you measure the current transients with the 1Ohm resistor?

I guess the inductor I used had too much DCR, which is why the problem went away...

**Comment by gkasprow** [comment] 2019-10-25 17:43
I used a big inductor that has very low ESR.
I also tried to remove one of the 220uF cap at the converter output and also add a soft start circuit for T5. None of them help, even combined.

**Comment by hartytp** [comment] 2019-10-25 17:44
@gkasprow out of curiosity, is the SS16 diode appropriate here? It has a max reverse voltage of 60V. Is that sufficient for PoE?

**Comment by gkasprow** [comment] 2019-10-25 17:46
Most switches use 48..57V so it should be fine. However, we can go for 80V version.

**Comment by hartytp** [comment] 2019-10-25 17:50
It would be interesting to see the current transients on a scope to try to understand what's going on that upsets the PoE switch. But, the only other thing I can think of is adding a ~10Ohm resistor, with a FET switch (+optocoupler) across it that can be used to short the resistor after power up.

**Comment by gkasprow** [comment] 2019-10-25 17:52
one moment.

**Comment by gkasprow** [comment] 2019-10-25 18:02
![tek00012](https://user-images.githubusercontent.com/4325054/67593336-464fc780-f762-11e9-8860-f39479a59625.png)
![tek00013](https://user-images.githubusercontent.com/4325054/67593338-48b22180-f762-11e9-88a6-f65d26e41b96.png)
![tek00014](https://user-images.githubusercontent.com/4325054/67593344-4bad1200-f762-11e9-8cd0-941b80ac3047.png)

So, we have 3.5A peak during on stage.

**Comment by hartytp** [comment] 2019-10-25 18:06
Wow that’s huge! Is that the module itself or our load? In that case it sounds like a current limiting resistor + fet may be the way to go...

**Comment by gkasprow** [comment] 2019-10-25 18:11
the module itself. Our load starts later. 10R gives far lower peak.

**Comment by gkasprow** [comment] 2019-10-25 18:11
![tek00015](https://user-images.githubusercontent.com/4325054/67593993-a3984880-f763-11e9-9e87-694e0319ffca.png)

**Comment by gkasprow** [comment] 2019-10-25 18:13
What's interesting the module starts with high current, than it's charging the output caps. Then current falls to low value and then out load starts.

**Comment by gkasprow** [comment] 2019-10-25 18:13
*our

**Comment by gkasprow** [comment] 2019-10-25 18:14
We can add FET + cap at the PoE module input as a soft start circuit. I'll try it in a moment.

**Comment by gkasprow** [comment] 2019-10-25 18:22
I will try with [this ](http://www.dectel.ru/components/transistor/pdf_mosfet/p4nk60z.pdf)MOSFET. I don't have many HV ones at home :)

**Comment by gkasprow** [comment] 2019-10-25 18:50
OK, so I tried schematic like this and it works
![obraz](https://user-images.githubusercontent.com/4325054/67596470-0e984e00-f769-11e9-84f6-53fc155253a3.png)

**Comment by hartytp** [comment] 2019-10-25 18:52
Cool! Great job @gkasprpw! Let’s go with that circuit and the beefier diodes for the next rev.

**Comment by gkasprow** [comment] 2019-10-25 18:52
I used 2002STP4NK60Z instead of STN2NF10 but it should not make any difference

**Comment by gkasprow** [comment] 2019-10-25 18:52
This influences all PoE circuits we have.

**Comment by hartytp** [comment] 2019-10-25 18:53
Yes. We’ll need to fix thermostat as well

**Comment by hartytp** [comment] 2019-10-25 18:54
So I think now all issues are fixed we can push out the new release quickly. That’s really great

**Comment by gkasprow** [comment] 2019-10-25 18:58
Connecting scope messes up PoE negotiation. One needs to use a battery-powered one. Essentially what it does with connected scope, it turns on the voltage which charges the capacitor and shorts the resistor and then it turns it off to turn it on again and then it fails because the resistor is shorted by MOSFET....
I think optocoupler is a better solution. I will implement both approaches so one has a choice.

**Comment by gkasprow** [comment] 2019-10-25 19:05
I will use this circuit
![obraz](https://user-images.githubusercontent.com/4325054/67597303-240e7780-f76b-11e9-8581-317d182386cb.png)

**Comment by hartytp** [comment] 2019-10-25 19:09
I’d still be inclined to hook up to cpu reset to make sure that the current limit is applied until all supplies are stable (in case the PoE is applied again before all caps have discharged)

Other than that lgtm

**Comment by gkasprow** [comment] 2019-10-25 19:09
OK, good idea.

**Comment by gkasprow** [comment] 2019-10-25 19:11
![obraz](https://user-images.githubusercontent.com/4325054/67597693-11e10900-f76c-11e9-9120-5e4f313252eb.png)

**Comment by jordens** [comment] 2019-10-25 19:34
https://www.electronicproducts.com/Semiconductors/Applications/Five_top_things_no_one_thinks_about_for_PoE_--_but_should.aspx

>  2) Inrush current protection is key: You might think that most PoE-enabled switches (known as power sourcing equipment or PSE) will control inrush current on the switch side, so client-side current-limiting isn’t too important. But what about your customers who use an inexpensive power injector in cases where PoE is not available from their Ethernet switch? Most low end PoE injectors (devices that sit in series between the wall jack and the client) don’t do any type of negotiation or “soft start” while applying power to a client. Make sure your PD can current limit so your capacitors don’t pop off the board during a live insertion, if your customer might use one of these injectors!

But I am surprised that the module itself is so aggressive.

**Comment by jordens** [comment] 2019-10-25 19:37
Not saying there's anything wrong with your circuit. But wouldn't inrush current limitation before the 440µF caps at the module output be a bit simpler?

**Comment by gkasprow** [comment] 2019-10-25 19:55
As I wrote a few posts above, I tried it already. I removed one 220uF cap and added a soft start but this did not help because is was not the cause of the problem. The inrush peak appears when the PoE module input caps are charged, far before it starts operation.

**Comment by jordens** [comment] 2019-10-25 20:07
Ah ok. I overlooked that. Then all good.

**Comment by sbourdeauducq** [comment] 2019-10-26 01:56
This sounds like shoddy design from the PoE module. Instead of adding workaround circuits, isn't it simpler and cleaner to use module from a different manufacturer, and test it carefully outside of the board in anticipation for similar shenanigans? The workaround circuits, if we do go this route, should probably be similarly tested as well.

**Comment by gkasprow** [comment] 2019-10-26 08:37
@sbourdeauducq this model of the switch is the only one that causes problems. I tried it with 4 other switches from other vendors and there were no issues. There is no guarantee that other PoE modules will work with your switch. The workaround is simple and it works. Other modules I found are much bigger and would require a serious redesign of the board and in case of the Thermostat, we would have to use a bigger enclosure. I also have proven PoE converter design build from discrete components but its overall cost is higher than this module cost. I've just tried and it does not work with this particular switch. 
The switch you have seem to not conform to specification because it behaves in a slightly bizarre way. It detects an overcurrent and switches the load off after 3s. It looks like it does not have active overcurrent protection, but an only software one.
The module we utilize I already used in a few other applications. Nobody complained so far. It is even installed in one  HEP experiment.

**Comment by gkasprow** [comment] 2019-10-26 08:38
I already tested this workaround circuit. I did it with 2 switches which I have at home.

**Comment by hartytp** [comment] 2019-10-26 09:42
> This sounds like shoddy design from the PoE module

I don't think this is a shoddy PoE module at all. I've been generally quite impressed with it. e.g. the fact that so far I haven't been able to see any increased noised in sensitive analog circuity when powered from PoE (even without the recommended EMI filter).

As @gkasprow says, we did look at a range of modules before closing this one, and there weren't a huge number of options that fitted in with our other requirements (e.g. space). So, I still think this is the best.

If we really want to change in future then, we can always design our own footprint compatible PoE module, but that's not a game I want to get into right now.

**Closed by hartytp** 2019-10-26 09:42 UTC
